name: Build APK 32bit
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-pip openjdk-17-jdk zip unzip git libffi-dev libssl-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev cmake

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36 virtualenv

      - name: Build 32-bit APK
        run: |
          rm -rf.buildozer bin
          yes | buildozer android debug

      - name: Upload 32-bit APK
        uses: actions/upload-artifact@v4
        with:
          name: jarvis-32bit-apk
          path: bin/*.apk
