name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk python3-pip python3-setuptools python3-dev build-essential libssl-dev libffi-dev libsqlite3-dev zip unzip libltdl-dev libbz2-dev libncurses5-dev libgdbm-dev liblzma-dev libreadline-dev tk-dev libgmp-dev libncursesw5-dev ccache libffi-dev libssl-dev automake autoconf libtool pkg-config
          pip install --upgrade pip
          pip install buildozer cython==0.29.36
      - name: Build APK
        run: |
          yes | sdkmanager --licenses || true
          buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
